# Generated by Django 6.0.6 on 2026-06-26 08:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtagindexpage_blogpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add additional text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}, null=True),
        ),
    ]
