# Generated by Django 6.0.6 on 2026-06-26 09:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogindexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='content',
            field=wagtail.fields.StreamField([('Title_and_Text', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add additional text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}, null=True),
        ),
    ]
