# Generated by Django 6.0.6 on 2026-06-27 13:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogindexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='content',
            field=wagtail.fields.StreamField([('Title_and_Text', 2), ('RichText', 3), ('SimpleRichText', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add additional text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('streams.blocks.RichTextBlock', (), {}), 4: ('streams.blocks.SimpleRichTextBlock', (), {})}, null=True),
        ),
    ]
