# Generated by Django 6.0.6 on 2026-06-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
    ]
