# Generated by Django 6.0.6 on 2026-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
