# Generated by Django 6.0.6 on 2026-06-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_body_remove_homepage_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
