# Generated by Django 6.0.6 on 2026-06-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_content_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home Pages'},
        ),
    ]
