# Generated by Django 6.0.6 on 2026-06-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homingggggg', 'verbose_name_plural': 'Home Pages'},
        ),
    ]
